name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false # 서브모듈 비활성화
      - name: Build and Deploy
        run: echo "Building and deploying..."
